### ISSUE TITLE
Fix websocket blocking

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#101]
The way we're doing threads now (using setImmediate) is actually working really well. What's not working really well is the way the data is being handled when it's changing.

For example - concerning the position system, even though the velocity and position are both 0 and stay 0, the client is getting *hammered* with thousands upon thousands of websocket events that effectively say "position has been changed to 0", since this is effectively what the position system is doing over and over again (setting the position to 0).

What are some ways we can fix this? I don't really have a good idea, besides checking if the value has changed before firing a websocket event. Even if we do that - we still need to figure out how to not block the client when values *are* updating rapidly. Suggestions?

**Comment by jextrevor** [comment]
I'm assigning Cayden to this one

**Comment by caydenlund** [comment]
The only time I see socket.emit() being used currently is in the system.js file. Is this still an issue that needs to be fixed? If it is, I think it's okay to remove the urgent label.

**Comment by jextrevor** [comment]
It's only used in the system.js file, but every single system inherits from system.js. And yes, it still needs to be fixed. Basically we need to throttle socket.emit. You can remove urgent if you want, but keep in mind this needs to be fixed before front end

**Comment by jextrevor** [comment]
Also, we don't need to throttle the socket emit for everything. We only need to throttle it for a few systems. I think we should create a separate function "set Throttled" that will still set every frame but will throttle the io.emit.

**Comment by jextrevor** [comment]
It's been 24 days. I'll handle this one. It's causing debugging problems for the frontend, and we can't do real work on the frontend until it's solved.
