### ISSUE TITLE
Create media manifest file

### ISSUE THREAD

**Issue by caydenlund** [X-12/andromeda#106]
We need to create a manifest file that will link to all of the required media (audio, images, etc.).
This could be a part of the config.js file, but I think it would also make sense to have a separate JSON file that config.js links to.

One quick question: Do we want to have separate manifest files (one for audio, one for images, one for videos, etc.) or one file?

**Comment by jextrevor** [comment]
Hmm... I would say probably in the same file, but under different sections?
