### ISSUE TITLE
Create Alerts System

### ISSUE THREAD

**Issue by DakotaHarward** [X-12/andromeda#26]
Create the alerts system. Refer to the [google doc](https://docs.google.com/document/d/1FCII9TvygKSvWBCU1Y61FxJJZJoyW4OTMDK9mGzbdJI/edit) for more information.

**Comment by jextrevor** [comment]
We should create two react components for this, one for setting the alert status, and one (or maybe more) for displaying it e.g. one that would change the stylesheet and/or create a red light and/or play sound effects.

**Comment by jextrevor** [comment]
Also - note that this issue is only labeled as backend. If you want to create a front end component, or you want to do both front end and back end, it would be smart to either create a new issue for it or change the labels of this one.

**Comment by jextrevor** [comment]
Has been fixed.
