### ISSUE TITLE
Create template for how other systems are referred to

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#29]
One thing we didn't come up on the 14th was a way for systems to refer to other systems.

One thing we could do is to pass certain required systems to module.exports, like so:
`module.exports = (io,Power) => {`
`...`
`turnOn(){`
`if(Power.Lights > 100){`
`etc`
___

`Power = require('./systems/power')(io)`
`Lights = require('./systems/lights')(io,Power)`

The problem with this is that we cannot have any circular dependencies. If Light needs to access the Power system but Power also needs to access the Light system, this won't work.

What we could do, and what I propose we do, is have a JSON containing all systems that is passed to module.exports:

`module.exports = (io,Ship) => {`
`...`
`turnOn(){`
`if(Ship.Power.Lights > 100){`
`etc`
___

`Ship = {}`
`Ship.Power = require('./systems/power')(io,Ship)`
`Ship.Lights = require('./systems/lights')(io,Ship)`

In this way, Lights has access to all systems it needs, as does Power.
What are your thoughts?

**Comment by DakotaHarward** [comment]
That looks good. Just to clarify, the Ship array is being created in the [main.js](https://github.com/X-12/andromeda/blob/master/server/main.js) file right?

**Comment by jextrevor** [comment]
Correct - the Ship JSON object is being created in main.js.
