### ISSUE TITLE
Add shared import file for stations

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#46]
We should create a default `station.js` that does things like connecting to SocketIO, and also importing SocketIO, default styles, and React libraries, so that we don't have to rewrite code.

Example:
station.js
```
const React = require('react')
...
const io = require('socket.io-client')("localhost:3000")
module.exports = io
```

captain.js
```
const station = require('./station')
```

**Comment by DakotaHarward** [comment]
I think this is a great idea. My vote is to implement.

**Comment by jextrevor** [comment]
There are a few problems with implementing this - namely:

- We have to refer to the imported modules anyway through station.whatevermodule, so it almost makes the code more unreadable.
- The babel preset we have for React components that allows us to use JSX expects React to be imported as React and not as station.React.

I say we proceed, but we only put things in `station.js` that make sense (things that don't need to be referenced, things that stand on their own, like default stylesheets)
