### ISSUE TITLE
Create config.js for constants used by systems

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#53]
Here's an idea - we create a file named `config.js` that stores things like initial power, initial health, required power, required health, etc.

Basically, it'd be a container for configuration data, and systems would import it and refer to it as needed.

config.js
```
module.exports = {
"PowerInitialAvailablePower":500,
"LifeSupportRequiredPower":50,
etc...
}
```

lifesupport.js
```
config = require('./config.js')
...
setStatus(value){
if(value == true){
if(Power.LifeSupport > config.LifeSupportRequiredPower){
...
```

**Comment by DakotaHarward** [comment]
I really love this idea. I can go ahead and just include this in issue #23 if you guys want.

**Comment by jextrevor** [comment]
I would separate it into different branches so we can work on the issues separately, and then make a new issue, e.g. "Refer to config values in Power system". Feel free to take charge of this issue though

**Comment by caydenlund** [comment]
'Kay. Looks good.

**Comment by jextrevor** [comment]
@DakotaHarward, when do you think you will have this done?

**Comment by DakotaHarward** [comment]
'tis done. (#76)
