### ISSUE TITLE
Create stations with respective names

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#8]
Stations need to be created with each of their respective names.

**Comment by jextrevor** [comment]
#7 should probably come before this so we don't get merge conflicts.

**Comment by jextrevor** [comment]
What shall we call stations? We need to be specific and consistent in the names we use.

**Comment by jextrevor** [comment]
@shrimpster00 @DakotaHarward I propose the following naming scheme:

Captain - captain.js
Navigations Officer - navigations.js
Tactical Officer - tactical.js
Operations Officer - operations.js
Engineer - engineer.js

Main View Screen - mvs.js
Flight Director - fd.js

**Comment by caydenlund** [comment]
Looks good

**Comment by jextrevor** [comment]
What do you think, @DakotaHarward?

**Comment by DakotaHarward** [comment]
I think we should call the Navigator, the Navigations Officer. That sounds better to me and it would be more consistent. Other than that though, it looks good.

**Comment by jextrevor** [comment]
Okay that sounds good. We'll also call the respective file navigations.js instead of navigator.js

**Comment by jextrevor** [comment]
I will take charge of this one
