### ISSUE TITLE
Transporter system

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#86]
We should think about a couple things - namely, what can be transported, where does it have to be, how we want to handle locations.

Also we should think about whether we want to do a shuttle system or not.

**Comment by DakotaHarward** [comment]
I'm going to combine this system with cargo (#85). In my head, all you're basically doing with cargo is transporting it to the different rooms in the ship. They will be different on the frontend, but as far as how they work with the server, it will be the same.
