### ISSUE TITLE
Where to store media?

### ISSUE THREAD

**Issue by jextrevor** [X-12/andromeda#93]
Media is kind of heavy. Do we want to store it inside the repository or somewhere else?

I ask because I want to start collecting media, and we really need to start collecting media.

My vote is to store it in the repo. It'll just be easier that way.

**Comment by jextrevor** [comment]
Git LFS looks like it could be of use.

**Comment by jextrevor** [comment]
I'll create the necessary changes in the repository - but for it to work correctly, everyone is going to have to head over to [here](https://git-lfs.github.com/) and follow the instructions to install there (all the way up to git lfs install, after that it should be fine)

**Comment by caydenlund** [comment]
Let me get this straight. All I have to do is run this curl script
<https://packagecloud.io/github/git-lfs/install> and then run git lfs
install in the repo?

**Comment by caydenlund** [comment]
That doesn't seem to be working quite right. How did you do that?

**Comment by jextrevor** [comment]
@DakotaHarward is creating a Mega account.

**Comment by DakotaHarward** [comment]
K, so the way that I imagine this to work is we sync the media folder in the repository with the media folder on Mega using the MEGAsync application. I'll create a branch that'll kinda show how this would work.

**Comment by jextrevor** [comment]
We've sufficiently set up MEGA and it seems to be working well. Closing.
